#!/usr/bin/perl
use strict;
use warnings;
use Chess::Coverage;
my $g = Chess::Coverage->new(
    'rnbqkbnr/pp1ppppp/8/2p5/4P3/5N2/PPPP1PPP/RNBQKB1R b KQkq - 1 2'
);
my $c = $g->coverage();
use Data::Dumper;$Data::Dumper::Sortkeys=1;die Dumper($c);
