#!/usr/bin/perl
use strict;
use warnings;
use Chess::Coverage;
my $g = Chess::Coverage->new();
my $c = $g->coverage(
#    pgn => 'rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3',
);
use Data::Dumper;$Data::Dumper::Sortkeys=1;die Dumper($c);
